version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    #command: dockerize -wait tcp://db:27017 -timeout 20s rake unicorn:start
    tty: true #pry-byebugを使えるようにする
    stdin_open: true
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      #ソケット通信用ファイルをnginxコンテナと共有
      - ./data/tmp-data:/var/www/shirasagi/tmp/sockets
      #画像データとかをnginxと共有
      - ./data/public/sites:/var/www/shirasagi/public/sites
      - ./data/private:/var/www/shirasagi/private

  db:
    image: mongo:3.4.5
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    restart: always #明示的にstopさせるまでリスタートする。（失敗するたび遅延あり）
    volumes:
      - ./data/tmp-data:/var/www/shirasagi/tmp/sockets
      - ./data/public/sites:/var/www/shirasagi/public/sites
    depends_on:
      - web
#volumes:
#  public-data:
#  tmp-data:
#  mongodb-data:
